//
//  FavoritesSceneWorker.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesSceneWorkerLogic {
    func fetchObjectsFromDatabasse(request: FavoritesScene.Database.Request) -> FavoritesScene.Database.Response
}

class FavoritesSceneWorker: FavoritesSceneWorkerLogic {
    var databaseManager: DatabaseManagerProtocol
    
    init(databaseManager: DatabaseManagerProtocol) {
        self.databaseManager = databaseManager
    }
    
    func fetchObjectsFromDatabasse(request: FavoritesScene.Database.Request) -> FavoritesScene.Database.Response {
        let objects = databaseManager.fetch(type: RealmPhotoModel.self)
        print("Objects \(objects)")
        print("Objects Count \(objects.count)")
        let response = FavoritesScene.Database.Response(objects: [])
        return response
    }
    
    func doSomeWork() {
    }
}
