//
//  FavoritesScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesScenePresentationLogic {
    func presentSomething(response: FavoritesScene.Database.Response)
    func handOverDatabaseObjects(response: FavoritesScene.Database.Response)
}

class FavoritesScenePresenter: FavoritesScenePresentationLogic {
    weak var viewController: FavoritesSceneDisplayLogic?

    // MARK: Parse and calc respnse from FavoritesSceneInteractor and send simple view model to FavoritesSceneViewController to be displayed

    func presentSomething(response: FavoritesScene.Database.Response) {
        //        let viewModel = FavoritesScene.Database.ViewModel()
        //        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func handOverDatabaseObjects(response: FavoritesScene.Database.Response) {
        let viewModel = response.objects.map { realmModel in
            let photoModel = PhotoModel(
                title: realmModel.title,
                owner: realmModel.owner,
                imageURL: realmModel.imageURL,
                image: UIImage(data: realmModel.image!) ?? UIImage(systemName: "photo.on.rectangle")!
            )
            return photoModel
        }
        viewController?.fetchCompleted(viewModel: FavoritesScene.Database.ViewModel(photos: viewModel))
    }
//
//    func presentSomethingElse(response: FavoritesScene.SomethingElse.Response) {
//        let viewModel = FavoritesScene.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
