//
//  FavoritesScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesScenePresentationLogic {
    func presentPhotos(response: FavoritesScene.Database.Response)
}

class FavoritesScenePresenter: FavoritesScenePresentationLogic {
    weak var viewController: FavoritesSceneDisplayLogic?
    
    func presentPhotos(response: FavoritesScene.Database.Response) {
        let viewModel = response.objects.map { realmModel in
            let photoModel = PhotoModel(
                id: realmModel.id,
                title: realmModel.title,
                owner: realmModel.owner,
                imageURL: realmModel.imageURL,
                image: UIImage(data: realmModel.image!) ?? UIImage(systemName: "photo.on.rectangle")!
            )
            return photoModel
        }
        viewController?.receivePhotos(viewModel: FavoritesScene.Database.ViewModel(photos: viewModel))
    }
}
