//
//  FavoritesScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesScenePresentationLogic {
    func presentSomething(response: FavoritesScene.Something.Response)
}

class FavoritesScenePresenter: FavoritesScenePresentationLogic {
    weak var viewController: FavoritesSceneDisplayLogic?

    // MARK: Parse and calc respnse from FavoritesSceneInteractor and send simple view model to FavoritesSceneViewController to be displayed

    func presentSomething(response: FavoritesScene.Something.Response) {
        let viewModel = FavoritesScene.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: FavoritesScene.SomethingElse.Response) {
//        let viewModel = FavoritesScene.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
