//
//  FavoritesSceneViewController.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesSceneDisplayLogic: AnyObject {
    func displaySomething(viewModel: FavoritesScene.Database.ViewModel)
    func fetchCompleted(viewModel: FavoritesScene.Database.ViewModel)
}

class FavoritesSceneViewController: UIViewController, FavoritesSceneDisplayLogic {
    var interactor: FavoritesSceneBusinessLogic?
    var router: (NSObjectProtocol & FavoritesSceneRoutingLogic & FavoritesSceneDataPassing)?
    
    let collectionView = PhotoCollectionViewController(collectionViewLayout: UICollectionViewLayout(), layoutSize: .large)
    @IBOutlet private var collectionViewContainer: UIView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        doSomething()
        //        doSomethingElse()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        loadPhotos()
    }
    
    func doSomething() {
        let request = FavoritesScene.Database.Request(type: RealmPhotoModel.self)
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: FavoritesScene.Database.ViewModel) {
        // nameTextField.text = viewModel.name
    }
    
    func loadPhotos() {
        interactor?.fetchObjectsFromDatabase(request: FavoritesScene.Database.Request(type: RealmPhotoModel.self))
    }
    
    func fetchCompleted(viewModel: FavoritesScene.Database.ViewModel) {
        collectionView.display(photos: viewModel.photos)
    }
    
    @objc private func leftBarButtonItemAction(_ sender: UIButton) {
        collectionView.changeLayout(to: .large)
    }
    
    @objc private func leftSecondaryBarButtonItemAction(_ sender: UIButton) {
        collectionView.changeLayout(to: .medium)
    }
}

extension FavoritesSceneViewController {
    func setupUI() {
        configureDependencies()
        addCollectionView()
        setupNavigationBar()
    }
    
    func setupNavigationBar() {
        let leftBarButton = UIButton(frame: CGRect(x: 0, y: 0, width: 40, height: 40))
        leftBarButton.setImage(UIImage(systemName: "list.bullet"), for: .normal)
        let leftSecondarytBarButton = UIButton(frame: CGRect(x: 0, y: 0, width: 40, height: 40))
        leftSecondarytBarButton.setImage(UIImage(systemName: "rectangle.grid.3x2"), for: .normal)
        let barButton = UIBarButtonItem(customView: leftBarButton)
        let secondarybarButton = UIBarButtonItem(customView: leftSecondarytBarButton)
        leftBarButton.addTarget(self, action: #selector(leftBarButtonItemAction), for: .touchUpInside)
        leftSecondarytBarButton.addTarget(self, action: #selector(leftSecondaryBarButtonItemAction), for: .touchUpInside)
        self.navigationItem.leftBarButtonItems = [barButton, secondarybarButton]
    }
    
    func configureDependencies() {
        ConfiguratorsLibrary.favoritesScene.configure(self)
    }
    
    private func addCollectionView() {
        addChild(collectionView)
        collectionViewContainer.addSubview(collectionView.view)
        collectionView.didMove(toParent: self)
        collectionView.view.translatesAutoresizingMaskIntoConstraints = false
        collectionView.view.equalConstraint(to: collectionViewContainer)
    }
}
