//
//  FavoritesSceneInteractor.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesSceneBusinessLogic {
    func fetchPhotos()
    func putInDataStore(photo: PhotoModel)
}

protocol FavoritesSceneDataStore {
    var selectedPhoto: PhotoModel { get set }
}

class FavoritesSceneInteractor: FavoritesSceneBusinessLogic, FavoritesSceneDataStore {
    var selectedPhoto = PhotoModel(id: "", title: "", owner: "", imageURL: "", image: UIImage())
    var presenter: FavoritesScenePresentationLogic?
    var worker: FavoritesSceneWorker?
    
    init(presenter: FavoritesScenePresentationLogic? = nil, worker: FavoritesSceneWorker? = nil) {
        self.presenter = presenter
        self.worker = worker
    }
    
    func fetchPhotos() {
        let request = FavoritesScene.Database.Request(type: RealmPhotoModel.self)
        let response = worker?.fetchObjectsFromDatabasse(request: request)
        presenter?.presentPhotos(response: response!)
    }
    
    func putInDataStore(photo: PhotoModel) {
        self.selectedPhoto = photo
    }
}
