//
//  FavoritesSceneModels.swift
//  Flickr
//
//  Created by Артур Кулик on 02.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FavoritesScene {
    // MARK: Use cases
    
    enum Database {
        struct Request {
            var type: RealmPhotoModel.Type
        }
        
        struct Response {
            var objects: [RealmPhotoModel]
        }
        
        struct ViewModel {
            var photos: [PhotoModel]
        }
    }
    
    //    enum SomethingElse
    //    {
    //        struct Request
    //        {
    //
    //        }
    //
    //        struct Response
    //        {
    //
    //        }
    //
    //        struct ViewModel
    //        {
    //
    //        }
    //    }
}
