//
//  MainScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScenePresentationLogic {
    func present(response: MainScene.FetchPhotos.Response)
}

class MainScenePresenter: MainScenePresentationLogic {
    weak var viewController: MainSceneDisplayLogic?
    
    func present(response: MainScene.FetchPhotos.Response) {
        let viewModel = MainScene.FetchPhotos.ViewModel(photoModel: response.photoModel)
        viewController?.successFetchHandler(viewModel: viewModel)
        
        if response.errorMessage != nil {
            let viewModel = MainScene.FetchPhotos.ViewModel(errorMessage: response.errorMessage)
            viewController?.errorFetchHandler(viewModel: viewModel)
        } else {
            let viewModel = MainScene.FetchPhotos.ViewModel(photoModel: response.photoModel!)
            viewController?.successFetchHandler(viewModel: viewModel)
        }
    }
}
