//
//  MainScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScenePresentationLogic {
    func presentSomething(response: MainScene.Something.Response)
}

class MainScenePresenter: MainScenePresentationLogic {
    weak var viewController: MainSceneDisplayLogic?

    // MARK: Parse and calc respnse from MainSceneInteractor and send simple view model to MainSceneViewController to be displayed

    func presentSomething(response: MainScene.Something.Response) {
        let viewModel = MainScene.Something.ViewModel(photos: response.photos)
        viewController?.updateUI(viewModel: viewModel)
    }
    
//    func presentSomethingElse(response: MainScene.SomethingElse.Response) {
//        let viewModel = MainScene.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
