//
//  MainSceneModels.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainScene {
    enum LoadPhotos {
        struct Request {
            var params: [String: Any] = [:]
            
            init(text: String, photosCount: Int) {
                self.params = [
                    "api_key": Constants.Api.flickrKey,
                    "format": "json",
                    "method": "flickr.photos.search",
                    "per_page": String(photosCount),
                    "text": text,
                    "nojsoncallback": "1"
                ]
            }
        }
        
        struct Response {
            var photos: [PhotoModel]?
            var errorMessage: String?
        }
        
        struct ViewModel {
            var errorMessage: String?
            var photos: [PhotoModel]?
        }
    }
}
