//
//  PhotoEditorSceneModels.swift
//  Flickr
//
//  Created by Артур Кулик on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhotoEditorScene {
    // MARK: Use cases

    enum InitialSetup {
        struct Request {
        }

        struct Response {
            var photoModel: PhotoModel
        }

        struct ViewModel {
            var photoModel: PhotoModel
        }
    }
        enum PhotoEditor {
            struct Request {
                var image: UIImage
                var filterIndex: Int
            }
    
            struct Response {
                var image: UIImage
            }
    
            struct ViewModel {
                var image: UIImage
            }
        }
    
    enum LoadFilters {
        struct Request {
            var image: UIImage
            var filters: [PhotoFilterType]
        }

        struct Response {
            var images: [UIImage]
        }

        struct ViewModel {
            var images: [UIImage]
        }
    }
    
    enum Gallery {
        struct Request {
            var image: UIImage
        }

        struct Response {
            var success: Bool
        }

        struct ViewModel {
            var success: Bool
        }
    }
}
