//
//  PhotoEditorScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoEditorScenePresentationLogic {
    func presentInitialSetup(response: PhotoEditorScene.InitialSetup.Response)
}

class PhotoEditorScenePresenter: PhotoEditorScenePresentationLogic {
    weak var viewController: PhotoEditorSceneDisplayLogic?

    // MARK: Parse and calc respnse from PhotoEditorSceneInteractor and send simple view model to PhotoEditorSceneViewController to be displayed

    func presentInitialSetup(response: PhotoEditorScene.InitialSetup.Response) {
        let viewModel = PhotoEditorScene.InitialSetup.ViewModel(photoModel: response.photoModel)
        viewController?.fillData(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: PhotoEditorScene.SomethingElse.Response) {
//        let viewModel = PhotoEditorScene.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
