//
//  PhotoEditorSceneRouter.swift
//  Flickr
//
//  Created by Артур Кулик on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotoEditorSceneRoutingLogic {
    func routeBack()
}

protocol PhotoEditorSceneDataPassing {
    var dataStore: PhotoEditorSceneDataStore? { get }
}

class PhotoEditorSceneRouter: NSObject, PhotoEditorSceneRoutingLogic, PhotoEditorSceneDataPassing {
    weak var viewController: PhotoEditorSceneViewController?
    var dataStore: PhotoEditorSceneDataStore?
    
    func routeBack() {
        DispatchQueue.main.async { [weak self] in
            self?.viewController?.navigationController?.popViewController(animated: true)
        }
    }
}
