//
//  PhotoEditorSceneWorker.swift
//  Flickr
//
//  Created by Артур Кулик on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PhotoEditorSceneWorker {
    var photoEditorService: PhotoEditorServiceProtocol!
    
    init(photoEditorService: PhotoEditorServiceProtocol!) {
        self.photoEditorService = photoEditorService
    }
    
    func applyFIlterToImage(image: UIImage, filterType: PhotoFilterType?) async -> PhotoEditorScene.PhotoEditor.Response {
        let image = await photoEditorService.applyBuiltInEffect(image: image, effectType: filterType)
        return PhotoEditorScene.PhotoEditor.Response(image: image)
    }
    
    func applyFilterToImageArray(image: UIImage, filterArray: [PhotoFilterType?]) async -> PhotoEditorScene.LoadFilters.Response {
        var filteredImages: [UIImage] = []
        for filter in filterArray {
            let image = await photoEditorService.applyBuiltInEffect(image: image, effectType: filter)
            filteredImages.append(image)
        }
        return PhotoEditorScene.LoadFilters.Response(images: filteredImages)
    }
}
