//
//  PhotoEditorSceneWorker.swift
//  Flickr
//
//  Created by Артур Кулик on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PhotoEditorSceneWorker {
    var photoEditorService: PhotoEditorServiceProtocol!
    
    init(photoEditorService: PhotoEditorServiceProtocol!) {
        self.photoEditorService = photoEditorService
    }
    func doSomeWork() {
    }
    //    func doSomeOtherWork() {
    //
    //    }
}
