//
//  PhotoEditorSceneViewController.swift
//  Flickr
//
//  Created by Артур Кулик on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoEditorSceneDisplayLogic: AnyObject {
    func fillData(viewModel: PhotoEditorScene.InitialSetup.ViewModel)
    func displaySomething(viewModel: PhotoEditorScene.InitialSetup.ViewModel)
    //    func displaySomethingElse(viewModel: PhotoEditorScene.SomethingElse.ViewModel)
}

class PhotoEditorSceneViewController: UIViewController, PhotoEditorSceneDisplayLogic {
    var interactor: PhotoEditorSceneBusinessLogic?
    var router: (NSObjectProtocol & PhotoEditorSceneRoutingLogic & PhotoEditorSceneDataPassing)?
    @IBOutlet private var imageView: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        initialUISetup()
    }
    
    func aboutFilters() {
        
    }
    
    func initialUISetup() {
        let request = PhotoEditorScene.InitialSetup.Request()
        interactor?.initialSetup(request: request)
    }
    
    func fillData(viewModel: PhotoEditorScene.InitialSetup.ViewModel) {
        imageView.image = viewModel.photoModel.image
    }
    
    func displaySomething(viewModel: PhotoEditorScene.InitialSetup.ViewModel) {
    }
}
