//
//  DetailSceneViewController.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailSceneDisplayLogic: AnyObject {
    func displaySomething(viewModel: DetailScene.Something.ViewModel)
}

class DetailSceneViewController: UIViewController, DetailSceneDisplayLogic {
    var interactor: DetailSceneBusinessLogic?
    var router: (NSObjectProtocol & DetailSceneRoutingLogic & DetailSceneDataPassing)?

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        let viewController = self
        let interactor = DetailSceneInteractor()
        let presenter = DetailScenePresenter()
        let router = DetailSceneRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    func doSomething() {
        let request = DetailScene.Something.Request()
        interactor?.doSomething(request: request)
    }
    //
    //    func doSomethingElse() {
    //        let request = DetailScene.SomethingElse.Request()
    //        interactor?.doSomethingElse(request: request)
    //    }

    // MARK: - display view model from DetailScenePresenter

    func displaySomething(viewModel: DetailScene.Something.ViewModel) {
        // nameTextField.text = viewModel.name
    }
    //
    //    func displaySomethingElse(viewModel: DetailScene.SomethingElse.ViewModel) {
    //        // do sometingElse with viewModel
    //    }
}
