//
//  DetailScenePresenter.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailScenePresentationLogic {
    func initialSetup(response: DetailScene.InitialSetup.Response)
    func showActivityView(response: DetailScene.Share.Response)
    func saveObjectToDatabaseCompleted(response: DetailScene.SaveToDB.Response)
    func openLinkInBrowser(request: DetailScene.OpenLink.Request)
}

class DetailScenePresenter: DetailScenePresentationLogic {
    weak var viewController: DetailSceneDisplayLogic?

    func initialSetup(response: DetailScene.InitialSetup.Response) {
        let viewModel = DetailScene.InitialSetup.ViewModel(photoModel: response.photoModel)
        viewController?.fillData(viewModel: viewModel)
    }
    
    func showActivityView(response: DetailScene.Share.Response) {
        guard response.isValidAddress else { return }
        let activityView = ActivityView(activityItems: [response.urlString], applicationActivities: [])
        let viewModel = DetailScene.Share.ViewModel(activityView: activityView)
        viewController?.showActivityView(viewModel: viewModel)
    }
    
    func saveObjectToDatabaseCompleted(response: DetailScene.SaveToDB.Response) {
        let viewModel = DetailScene.SaveToDB.ViewModel(isSaved: true)
        viewController?.savingToDBCompleted(viewModel: viewModel)
    }
    
    func openLinkInBrowser(request: DetailScene.OpenLink.Request) {
        UIApplication.shared.open(URL(string: request.urlString)!)
    }
}
