//
//  DetailSceneInteractor.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailSceneBusinessLogic {
    func doSomething(request: DetailScene.Something.Request)
//    func doSomethingElse(request: DetailScene.SomethingElse.Request)
}

protocol DetailSceneDataStore {
    // var name: String { get set }
}

class DetailSceneInteractor: DetailSceneBusinessLogic, DetailSceneDataStore {
    var presenter: DetailScenePresentationLogic?
    var worker: DetailSceneWorker?
    // var name: String = ""

    // MARK: Do something (and send response to DetailScenePresenter)

    func doSomething(request: DetailScene.Something.Request) {
        worker = DetailSceneWorker()
        worker?.doSomeWork()

        let response = DetailScene.Something.Response()
        presenter?.presentSomething(response: response)
    }
    //
    //    func doSomethingElse(request: DetailScene.SomethingElse.Request) {
    //        worker = DetailSceneWorker()
    //        worker?.doSomeOtherWork()
    //
    //        let response = DetailScene.SomethingElse.Response()
    //        presenter?.presentSomethingElse(response: response)
    //    }
}
