//
//  DetailSceneModels.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailScene {
    enum InitialModel {
        struct Request {
        }

        struct Response {
            var photoModel: PhotoModel
        }

        struct ViewModel {
            var photoModel: PhotoModel
        }
    }
    
    enum Share {
        struct Request {
            var urlString: String
        }

        struct Response {
            var photoModel: String
        }

        struct ViewModel {
            var activityController: UIActivityViewController
        }
    }
}
