//
//  DetailSceneViewController.swift
//  Flickr
//
//  Created by Артур Кулик on 01.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailSceneDisplayLogic: AnyObject {
    func displaySomething(viewModel: DetailScene.InitialModel.ViewModel)
}

class DetailSceneViewController: UIViewController, DetailSceneDisplayLogic {
    var interactor: DetailSceneBusinessLogic?
    var router: (NSObjectProtocol & DetailSceneRoutingLogic & DetailSceneDataPassing)?
    
    @IBOutlet private var imageView: UIImageView!
    @IBOutlet private var titleText: UILabel!
    @IBOutlet private var owner: UILabel!
    @IBOutlet private var address: UITextView!
    
    @IBAction private func shareButtonAction(_ sender: UIButton) {
        let items = ["Text For Share"]
        let avc = UIActivityViewController(activityItems: items, applicationActivities: nil)
        self.present(avc, animated: true)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        configureViews()
        print("Detail scene did load")
    }
    
    func doSomething() {
        let request = DetailScene.InitialModel.Request()
        interactor?.initialSetup(request: request)
    }
    
    func configureViews() {
        address.isEditable = false
        address.dataDetectorTypes = .link
    }
    
    func displaySomething(viewModel: DetailScene.InitialModel.ViewModel) {
        imageView.image = viewModel.photoModel.image
        titleText.text = viewModel.photoModel.title
        owner.text = viewModel.photoModel.owner
        address.text = viewModel.photoModel.address
    }
}
